### ISSUE TITLE
Manual install leads to Error: Cannot find module './optparse'

### ISSUE THREAD

**Issue by jasonkuhrt** [satyr/coco#45]
When installing coco manually using readme instructions, the following occurs: 

```
node.js:63
    throw e;
    ^s:275:15)
    at require (node.js:411:14)
    at Object.<anonymous> (/Users/KUHRT/coco/bin/coco:20:5)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at loadModule (node.js:283:14)
    at require (node.js:411:14)
    at Object.<anonymous> (/Users/KUHRT/coco/bin/coke:11:15)
    at Module._compile (node.js:462:23)
```

I can overcome this by manually copying the optpase file from the lib directory to the bin directory. I also npm'd optparse but haven't tried loading the module from there (after I realized the problem code was using a local path). I see that you've symlinked the coke file to bin so I am not sure why this is happening. 

Am I doing something wrong?

**Comment by satyr** [comment]
Do you use node.js 0.4.0 or higher? Earlier versions didn't follow symlinks for `require` I believe.

**Comment by jasonkuhrt** [comment]
Solved. Thanks again.
